Setup linters, rubocop, stylelinrc
NurkaAmre/blog-app pull request #1
Opened 2023-01-24 16:27 UTC by NurkaAmre

### In this PR I did following features: 
blah blah blah

2023-01-24 18:34 UTC, ShadyShawkat requested changes
## Hi @NurkaAmre, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 18:34 UTC, ShadyShawkat commented on db/migrate/20230124180818_create_comments.rb
> +end
- [ ] Please make sure that the comment has a foreign key reference to the posts table, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) ERD Diagram.

2023-01-24 18:34 UTC, ShadyShawkat commented on db/migrate/20230124181134_create_posts.rb
> +
- [ ] Kindly make sure that the reference foreign key is tied to a table. Here you're referencing a table called "authors" which doesn't exist. (please do this to all tables that have a reference to the "users" table)

- [HINT] You can use the following syntax to do so.
```ruby
t.references :author, foreign_key: { to_table: 'users' }
```

2023-01-25 06:25 UTC, AshakaE commented
Hi @NurkaAmre , 

### Highlights ✨ 

- Pull request 👌 
- Git flow ✅ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 06:35 UTC, merged